### ISSUE TITLE
What is h_common ?

### ISSUE THREAD

**Issue by askz** [nebula0225/customgrapi#9]
Hello, in the HashtagMixin, you import h_common as common. What is it ? Cant find the ref anywhere.
Thanks.

https://github.com/nebula0225/customgrapi/blob/fafb0e673d475c8a054ffc83a1c00e521651dec6/mixins/hashtag.py#L13

**Comment by nebula0225** [comment]
Hello,
The h_common file contains commonly used functions such as opening json, checking spam, checking private proxy information, etc.

**Comment by askz** [comment]
@nebula0225 - thanks, but where is it?

**Comment by nebula0225** [comment]
@askz I can't share h_common file cause include personal information
if you want to use file that imported h_common just remove h_common's method
additionally code modifications may be required.
